SELECT
    IT.INVENTORYID
    , IT.TRANSACTION_ID
    , T.TRANSACTION_DT
    , T.USRNAM
    , IT.AMOUNTLEFT
    , IT.AMOUNT_UNIT_CODE
    , T.TRANSACTION_TYPE
    , IT.COMMENTS
    , IT.CONTAINER_POS_Y
    , IT.CONTAINER_POS_X
    , IT.FLAG_CURRENT
    , PARENT_CONTAINER.EXTERNAL_CODE AS [BOX_NAME]
    , PARENT_CONTAINER.INVENTORY_CODE AS [BOX_CODE]
    , POSITION.ORDINAL AS [BOX_POS]
    , RACK.LOCATION_NAME AS [LOCATION_NAME]
    , RACK.LONGNAME AS [LONGNAME]
FROM INVENTORY_TRANSACTIONS_VLA IT
    LEFT JOIN TRANSACTIONS T ON IT.TRANSACTION_ID = T.TRANSACTION_ID
    INNER JOIN INVENTORY_VLA INV ON INV.INVENTORYID = IT.INVENTORYID
    INNER JOIN CENTRALRECEIVING_VLA CR ON CR.EXTERNAL_ID = INV.EXTERNAL_ID
    -- Join parent container for each transaction
    OUTER APPLY (SELECT PI.MATCODE, PI.EXTERNAL_CODE, PI.INVENTORYID, PI.INVENTORY_CODE
    FROM INVENTORY PI
    WHERE PI.INVENTORYID = IT.CONTAINER_INVENTORYID AND PI.INVENTORYID <> IT.INVENTORYID) AS PARENT_CONTAINER
    LEFT JOIN MATERIALS M ON PARENT_CONTAINER.MATCODE = M.MATCODE
    -- Join direct location for each transaction
    LEFT JOIN LOCATIONS RACK ON IT.LOCATIONCODE = RACK.LOCATIONCODE
    OUTER APPLY (SELECT ((IT.CONTAINER_POS_Y - 1) * M.CONTAINER_AXIS_X_SIZE + IT.CONTAINER_POS_X) AS ORDINAL) AS POSITION
WHERE
    CR.LAST_NAME = :trial_code
ORDER BY
    IT.INVENTORYID, IT.TRANSACTION_ID
