SELECT
    TR.TRIAL_CODE
    , CR.SUBJECTID
    , CR.FIRST_NAME AS [LABID]
    , SC.CONTAINERID AS [CID]
    , SC.SAMPLETYPE
    , CC.PRESERVATIVE
    , IT.AMOUNTLEFT
    , IT.AMOUNT_UNIT_CODE
    , IT.THAWCOUNT
    , INV.EXTERNAL_CODE AS [SEQ]
    , CAST(INV.EXTERNAL_CODE AS INT) AS [SEQ_NUM]
    , (
        CASE
            WHEN FREEZER.LOCATIONCODE IS NOT NULL THEN FREEZER.LOCATION_NAME
            ELSE SHELF.LOCATION_NAME
        END
    ) AS [FREEZER]
    , (
        CASE
            WHEN FREEZER.LOCATIONCODE IS NOT NULL THEN SHELF.LOCATION_NAME
            ELSE RACK.LOCATION_NAME
        END
    ) AS [SHELF]
    , (
        CASE
            WHEN FREEZER.LOCATIONCODE IS NOT NULL THEN RACK.LOCATION_NAME
            ELSE NULL
        END
    ) AS [RACK]
    , CR.FOLDERNO AS [ACCESSION]
    , CR.DATE_COLLECTED
    , CR.DATE_RECEIVED
    , PARENT_CONTAINER.EXTERNAL_CODE AS [BOX_NAME]
    , PARENT_CONTAINER.INVENTORY_CODE AS [BOX_CODE]
    , POSITION.ORDINAL AS [BOX_POS]
    , SC.RECEIVEDCONDITION AS [RECEIVED_CONDITION]
    , INV_META.FIELD16 AS [SAMPLE_CONDITION]
    , INV_META.FIELD01 AS [COMMENTS]
    , TMS.MSDESCRIPTION AS [MS_VISIT]
    , TMS.TRIAL_MASTER_SCHEDULE_ID AS [TMS_ID]
    , TETP.CODE AS [TP_CODE]
    , TETP.VISIT AS [TP_VISIT]
    , TETP.DESCRIPTION AS [TP_DESC]
    , TE.ELEMENT_NAME AS [TE_NAME]
    , CR_META.FIELD03 AS [NICKNAME]
    , CR_META.FIELD02 AS [CR_VISIT]
    , IT.CONSENT_TYPE
    , RACK.LOCATIONCODE AS [RACK_CODE]
    , SHELF.SORTER AS [SHELF_SORT]
    , RACK.SORTER AS [RACK_SORT]
    , SC.CONTAINERMATCODE
    , PARENT_CONTAINER.MATCODE
    , IT.CONTAINER_POS_Y
    , M.CONTAINER_AXIS_Y_SIZE
    , IT.CONTAINER_POS_X
    , M.CONTAINER_AXIS_X_SIZE
    , CR.LAST_NAME AS [LAST_NAME]
    , CR.RASCLIENTID AS [STUDY_SITE]
    , RACK.LONGNAME
    , RACK.LONGCODE
    , ROOMS.ROOM_NAME
    , ROOMS.ROOM_CODE
    , BUILDINGS.BUILDING_NAME AS BUILDING_NAME
    , BUILDINGS.BUILDING_CODE AS BUILDING_CODE
    , CR.ARCSTATUS AS [ARCHIVE_STATUS]
    , INV.INVENTORYID AS [VIAL_CONTAINER_INV_ID]
    , PARENT_CONTAINER.INVENTORYID AS [PARENT_CONTAINER_INV_ID]
    , CR.ORIGREC AS [CR_ORIGREC]
FROM INVENTORY_VLA INV
    INNER JOIN CENTRALRECEIVING_VLA CR ON CR.EXTERNAL_ID = INV.EXTERNAL_ID
    INNER JOIN SAMPLECONTAINERS_VLA SC ON SC.INVENTORYID = INV.INVENTORYID
    INNER JOIN INVENTORY_TRANSACTIONS_VLA IT ON IT.INVENTORYID = INV.INVENTORYID AND IT.FLAG_CURRENT = 1
    OUTER APPLY (SELECT PI.MATCODE, PI.EXTERNAL_CODE, PI.INVENTORYID, PI.INVENTORY_CODE
    FROM INVENTORY PI
    WHERE PI.INVENTORYID = IT.CONTAINER_INVENTORYID AND PI.INVENTORYID <> INV.INVENTORYID) AS PARENT_CONTAINER
    OUTER APPLY (SELECT PIT.LOCATIONCODE, PIT.COMMENTS
    FROM INVENTORY_TRANSACTIONS PIT
    WHERE PIT.INVENTORYID = PARENT_CONTAINER.INVENTORYID AND PIT.FLAG_CURRENT = 1) AS PARENT_CONTAINER_IT
    INNER JOIN METADATA CR_META ON CR_META.ID = CR.METADATA_GUID
    INNER JOIN METADATA INV_META ON INV_META.ID = INV.METADATA_GUID
    INNER JOIN TRIAL_MASTER_SCHEDULE TMS ON TMS.TRIAL_MASTER_SCHEDULE_ID = CR.TRIAL_MASTER_SCHEDULE_ID
    LEFT JOIN TRIAL_ELEMENT_TIMEPOINT TETP ON TETP.TRIAL_ELEMENT_TP_ID = TMS.TRIAL_ELEMENT_TP_ID
    LEFT JOIN TRIAL_ELEMENT TE ON TE.TRIAL_ELEMENT_ID = TETP.TRIAL_ELEMENT_ID
    INNER JOIN TRIAL TR ON TMS.TRIAL_ID = TR.TRIAL_ID
    LEFT JOIN MATERIALS M ON PARENT_CONTAINER.MATCODE = M.MATCODE
    LEFT JOIN CONTAINERS_CONDITION CC ON CC.CONTCODE = SC.CONTCODE
    OUTER APPLY (SELECT ((IT.CONTAINER_POS_Y - 1) * M.CONTAINER_AXIS_X_SIZE + IT.CONTAINER_POS_X) AS ORDINAL) AS POSITION
    -- FIRST-LEVEL LOCATION (RACK)
    LEFT JOIN LOCATIONS RACK ON IT.LOCATIONCODE = RACK.LOCATIONCODE
    -- SECOND-LEVEL LOCATION (SHELF)
    LEFT JOIN LOCATIONS SHELF ON RACK.PARENT_LOCATION_CODE = SHELF.LOCATIONCODE
    -- THIRD-LEVEL LOCATION (FREEZER)
    LEFT JOIN LOCATIONS FREEZER ON SHELF.PARENT_LOCATION_CODE = FREEZER.LOCATIONCODE
    LEFT JOIN ROOMS ON FREEZER.ROOM_ID = ROOMS.ROOM_ID
    LEFT JOIN BUILDINGS ON ROOMS.BUILDING_ID = BUILDINGS.BUILDING_ID
WHERE
    -- Yes, we're filtering by last name to get trial code... don't ask.
    -- And yes, this is safe in this context - we control TRIAL_CODE input elsewhere.
    -- Plus, aioodbc parameterization doesn't work in this scenario.
    CR.LAST_NAME IN (?)
